### ISSUE TITLE
Tabs or Spaces

### ISSUE THREAD

**Issue by clohfink** [phact/CassandraDataModeler#33]
Kinda minor issue. In sizer.js there is some methods using tabs and some using spaces, and some intertwined.

![never both](https://imgur.com/JGU8qiE.png)

**Comment by phact** [comment]
Let's do spaces.

**Comment by phact** [comment]
https://github.com/phact/CassandraDataModeler/commit/6afbee6760689166ee822eb9d063c47defa576fe
